### PR TITLE
Update regex to match zero or more spaces before ip.

### LINKED ISSUE #40: TorProject ExitAddresses do not match regex in reputations lists parser
https://github.com/awslabs/aws-waf-security-automations/blob/beca5eb31b55dcba291b5ad1a91a0ba687292402/source/reputation-lists-parser/reputation-lists-parser.js#L112

The regular expression there does not match the TorProjects list of ExitAddresses: https://check.torproject.org/exit-addresses

### PR DESCRIPTION
**Pull request by dgtanner**
Fix regex to work with the format in https://check.torproject.org/exit-addresses.
fixes #40

### CODE REVIEW

**Comment by hvital** [comment]
Hi @dgtanner 

Thanks for this PR. Will include this in the next update.

btw, do you know a sample of an [exite-address](https://check.torproject.org/exit-addresses) that was failing to be imported before this fix? Would like to add a new test case to cover this.

**Comment by dgtanner** [comment]
@hvital
All of the Tor ips had the issue for me.

Also, for the scanners and probes, have you considered using Athena instead of python in a lambda?  

We have a very large amount of traffic behind several load balancers.  This causes race conditions with the log parsing and ips never end up getting blacklisted unless I introduce random sleeps.  I may write a solution using Athena as time permits.

Awesome project, stellar work!

David

**Comment by hvital** [comment]
Thanks @dgtanner 

Agre! It's time to think about using Athena or CloudWatch Logs Insights. Need to double check if this would impact any region that is currently supported.

Will add this as feature request to be evaluated before next update. ok?

**Comment by dgtanner** [comment]
> Thanks @dgtanner
> 
> Agre! It's time to think about using Athena or CloudWatch Logs Insights. Need to double check if this would impact any region that is currently supported.
> 
> Will add this as feature request to be evaluated before next update. ok?

Sounds great.  Thanks!

**Comment by thiagodiogo** [comment]
Tested it last week and found it the hard way (after deploy it) :)

@hvital, please merge it as a bug fix to avoid people to use the wrong one.

Thank you!

**Comment by baversjo** [comment]
Can also confirm that this change makes the WAF block tor usage. Without this change in place, I was able to access my app through tor.

**Comment by hvital** [comment]
Incorporated to v2.3.0 ([here](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/source/reputation-lists-parser/reputation-lists-parser.js#L113)). Thanks!

**Pull request closed without merging**
