### PR TITLE
Support node v10

### PR DESCRIPTION
**Pull request by jgeurts**
*Issue #:* #99

*Description of changes:*

* Support node v10
* Remove async library
* Update javascript syntax to leverage async/await and classes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jgeurts** [comment]
Anything needed for this PR?

**Comment by jgeurts** [comment]
@shsenior is there anything I can do to get this merged?

**Comment by jgeurts** [comment]
@hvital is there anything I can do to get this merged?

**Comment by knihit** [comment]
Thank you for the PR. We will review and plan for it in a future release

**Comment by knihit** [comment]
Hi @jgeurts, the solution has been updated to Node10.x.

**Comment by jgeurts** [comment]
@knihit the async library really should be removed. It's garbage and swallows exceptions thrown in the callback functions. With node 10+, there's no reason to use the async library anymore

**Comment by knihit** [comment]
Hi @jgeurts, agree to your comments. We will plan this in the upcoming releases

**Pull request closed without merging**
